### ISSUE TITLE
RangeError: Maximum call stack size exceeded  at (miraplayer.min.1_3_7.js:22722:1)

### ISSUE THREAD

**Issue by persec10000** [miravideo/miravideo.github.io#1]
I've integrated miraplayer.min.js to my angular project, 
When I call creator.toJson() and creator.toMiraML(), Following error is occured.

miraplayer.min.1_3_7.js:40190 RangeError: Maximum call stack size exceeded
    at Function.entries (<anonymous>)
    at r (miraplayer.min.1_3_7.js:22722:1)

**Comment by persec10000** [comment]
I have to add exception code for it as following.
toJson(t = !1){
...
if(t.constructor.name != "ZoneTask" && t.constructor.name != "Zone") // added this line
{
for (const [e, n] of Object.entries(t)) "innerHTML" === e ? delete t[e] : n && "object" == typeof n && r(n)
}
...
}
